name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: the-orrery/.github/.github/workflows/python-ci.yml@v8
    with:
      ruff-extend-ignore: "['TRY003']"
      ruff-extend-per-file-ignores: "{'tests/**'=['ARG']}"
